"""OS boundaries. Domain and use cases never import native APIs."""
from typing import ContextManager, Protocol


class Lease(Protocol):
    def child_options(self) -> ContextManager[dict]: ...


class FileLocks(Protocol):
    def acquire(self, path, *, wait: bool = False) -> ContextManager[Lease]: ...


class TerminalInput(Protocol):
    def session(self) -> ContextManager[None]: ...
    def read_key(self, timeout: float = 0.2) -> str | None: ...


class AppPaths(Protocol):
    def data_directory(self): ...
    def legacy_directory(self): ...


class ProcessControl(Protocol):
    def detached_options(self) -> dict: ...
    def identity(self, pid: int, config) -> float | None: ...
    def stop(self, pid: int, config, created_at: float | None = None) -> None: ...
