from typing import Protocol

from codex_switch.domain.models import Account, Preferences, ProxyStatus, Server


class Settings(Protocol):
    def load(self) -> Preferences: ...
    def save(self, preferences: Preferences) -> None: ...


class Servers(Protocol):
    def list(self) -> list[Server]: ...
    def save(self, server: Server) -> None: ...


class Accounts(Protocol):
    def list(self, *, refresh: bool = False, proxy: str | None = None) -> list[Account]: ...
    def switch(self, key: str, *, proxy: str | None = None) -> None: ...
    def login(self, *, proxy: str | None = None) -> None: ...


class Proxy(Protocol):
    def status(self) -> ProxyStatus: ...
    def validate(self, server: Server) -> None: ...
    def start(self, server: Server) -> ProxyStatus: ...
    def stop(self) -> None: ...
    def check(self) -> bool: ...


class Codex(Protocol):
    def run(self, args: list[str], *, proxy: str | None = None) -> int: ...


class Diagnostics(Protocol):
    def dependencies(self) -> dict[str, str]: ...
