from typing import Protocol

from codex_switch.domain.models import Account, Preferences, ProxyStatus, Server
from codex_switch.domain.profiles import ProfileStatus


class Settings(Protocol):
    def load(self) -> Preferences: ...
    def save(self, preferences: Preferences) -> None: ...


class Servers(Protocol):
    def list(self) -> list[Server]: ...
    def save(self, server: Server) -> None: ...


class Accounts(Protocol):
    def list(self, *, refresh: bool = False, proxy: str | None = None) -> list[Account]: ...
    def switch(self, key: str, *, proxy: str | None = None) -> None: ...
    def login(self, *, proxy: str | None = None) -> None: ...


class Proxy(Protocol):
    def status(self) -> ProxyStatus: ...
    def validate(self, server: Server) -> None: ...
    def start(self, server: Server) -> ProxyStatus: ...
    def stop(self) -> None: ...
    def check(self) -> bool: ...


class Codex(Protocol):
    def run(self, args: list[str], *, proxy: str | None = None) -> int: ...


class Diagnostics(Protocol):
    def dependencies(self) -> dict[str, str]: ...


class Profiles(Protocol):
    def names(self) -> list[str]: ...
    def inspect(self, name: str, *, refresh: bool = False, proxy: str | None = None) -> ProfileStatus: ...
    def login(self, name: str, *, proxy: str | None = None) -> ProfileStatus: ...
    def run(self, name: str, args: list[str], *, proxy: str | None = None) -> int: ...
    def rename(self, name: str, label: str) -> None: ...
    def remove(self, name: str) -> None: ...


class Projects(Protocol):
    def current(self) -> str: ...
    def bound(self) -> str | None: ...
    def bind(self, name: str) -> None: ...
    def unbind(self) -> None: ...
