"""The monitor owns a virtual screen; OS adapters only transport terminal bytes."""
from typing import Protocol


class PseudoTerminal(Protocol):
    pid: int
    def read(self, timeout: float) -> bytes: ...
    def write(self, data: bytes) -> None: ...
    def resize(self, rows: int, columns: int) -> None: ...
    def poll(self) -> int | None: ...
    def close(self) -> None: ...
